#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16GB
#SBATCH --time=1:00:00
#SBATCH --account=qcb_640

module purge
module load gcc/11.2.0 openblas/0.3.18 python/3.9.6 r/4.1.2

python3 script.py